-- Migration 017: remote borrower confirmation for mashonisa loans.
--
-- Phase 2 of borrower identity. A mashonisa can send a WhatsApp link to
-- a REMOTE borrower who is NOT a KasiKash user. The borrower opens a
-- public, no-login page and submits their SA ID + name + agreement.
--
-- Security model: because the borrower has no account, they must NOT be
-- able to write to mashonisa_loans directly (RLS rejects it). Instead
-- they call two SECURITY DEFINER functions exposed to the `anon` role
-- that are tightly scoped — they only ever touch the SINGLE loan whose
-- secret confirmation_token matches AND which is still 'awaiting'.
--
-- The token is an unguessable UUID generated by the lender's app and
-- shared only with the intended borrower. Confirming CONSUMES the token
-- (sets it null) so the link can't be replayed.
--
-- ⚠️ This grants EXECUTE on two functions to anon. It grants NO table
-- access — anon still cannot select/update mashonisa_loans directly.
-- Worth a security review before going wide (and add rate-limiting at
-- the edge if abuse becomes a concern).
--
-- Idempotent: safe to re-run.

-- 1) Secret token column + widen confirmation states to include 'remote'.
alter table public.mashonisa_loans
  add column if not exists confirmation_token text;

alter table public.mashonisa_loans
  drop constraint if exists mashonisa_loans_borrower_confirmation_check;

alter table public.mashonisa_loans
  add constraint mashonisa_loans_borrower_confirmation_check
  check (
    borrower_confirmation in ('in_person', 'remote', 'awaiting', 'unverified')
  );

-- Fast, private lookup by token (only awaiting loans carry one).
create index if not exists mashonisa_loans_confirmation_token_idx
  on public.mashonisa_loans (confirmation_token)
  where confirmation_token is not null;

-- 2) Read the minimal summary a borrower needs in order to confirm.
--    Returns at most one row, and only while the loan is 'awaiting'.
--    Casts guard against date/numeric column-type differences.
create or replace function public.get_mashonisa_loan_for_confirmation(p_token text)
returns table (
  borrower_name text,
  amount_lent numeric,
  agreed_repayment_date text
)
language sql
security definer
set search_path = public
as $$
  select
    l.borrower_name::text,
    l.amount_lent::numeric,
    l.agreed_repayment_date::text
  from public.mashonisa_loans l
  where l.confirmation_token = p_token
    and l.borrower_confirmation = 'awaiting'
  limit 1;
$$;

-- 3) Apply the borrower's confirmation. Updates ONLY the one awaiting
--    loan matching the token: records the self-entered ID + name +
--    consent, marks it 'remote', and consumes the token. Returns true
--    on success, false when nothing matched (wrong/expired token, or
--    already confirmed).
create or replace function public.confirm_mashonisa_loan(
  p_token text,
  p_id_number text,
  p_name text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  -- Cheap server-side guards; the app validates the SA ID checksum too.
  if p_token is null or p_id_number is null or length(p_id_number) <> 13 then
    return false;
  end if;

  update public.mashonisa_loans
     set borrower_id_number = p_id_number,
         borrower_name = coalesce(nullif(btrim(p_name), ''), borrower_name),
         borrower_consent_at = now(),
         borrower_confirmation = 'remote',
         confirmation_token = null
   where confirmation_token = p_token
     and borrower_confirmation = 'awaiting';

  get diagnostics v_count = row_count;
  return v_count > 0;
end;
$$;

-- 4) Expose ONLY these two functions to anonymous callers. No table
--    grants are added.
grant execute on function public.get_mashonisa_loan_for_confirmation(text)
  to anon, authenticated;
grant execute on function public.confirm_mashonisa_loan(text, text, text)
  to anon, authenticated;

do $$
begin
  raise notice '── Mashonisa remote borrower confirmation applied ──';
  raise notice 'mashonisa_loans.confirmation_token + get/confirm RPCs (anon EXECUTE) created';
end
$$;
